[FAB-17765] add R/W in marbles02 init() for system test
hyperledger/fabric-test pull request #191
Opened 2020-05-18 20:11 UTC by dongmingh

This PR is to add READ/WRITE READ/WRITE in init() of marbles02
A example is given in PTE/marblesInputs
If args length is not 4, then init() will perform no-op as it does today

Signed-off-by: Dongming Hwang <dongming@ibm.com>

2020-05-18 21:21 UTC, lindluni requested changes
Couple real quick comments, can you run `gofmt -l -s -w chaincodes/marbles02/go/marbles_chaincode.go` to properly format the file.

Thanks!

2020-05-18 21:21 UTC, btl5037 commented on chaincodes/marbles02/go/marbles_chaincode.go
> +        queryString := fmt.Sprintf("{\"selector\":{\"docType\":\"marble\",\"owner\":\"%s\",\"size\":\"35\"}}", owner)
You can use backticks to escape the entire string ```fmt.Sprintf(`{"selector" {"docType":"marble","owner":"%s","size":"35"}}`, owner)```

2020-05-18 21:21 UTC, btl5037 commented on chaincodes/marbles02/go/marbles_chaincode.go
> +
Remove extra blank line

2020-05-20 12:54 UTC, dongmingh commented
> Couple real quick comments, can you run `gofmt -l -s -w chaincodes/marbles02/go/marbles_chaincode.go` to properly format the file.
> 
> Thanks!

done, thx

2020-05-20 15:02 UTC, lindluni approved these changes

2020-05-20 15:02 UTC, merged