[FAB-17103] Add upgrade network option to operator
hyperledger/fabric-test pull request #30
Opened 2019-12-12 18:49 UTC by suryalnvs

Adding upgrade network option to operator. For example:
`go run main.go -i <network-spec-file> -a upgradeNetwork`

Above command will take down existing fabric network, upgrade
all peer db's, relaunch fabric network using 2.0 images, update
capabilities for orderer system channel and all application
channels, update policies for consortium on orderer system
channel, update policies for each organization, app policies,
acls on all application channels.

Signed-off-by: Surya Lanka <suryalnvs@gmail.com>

2019-12-12 19:52 UTC, suryalnvs commented
@bharadwajambati95

2019-12-17 21:43 UTC, scottz64 requested changes

2019-12-17 21:43 UTC, scottz64 commented on regression/smoke/runSmokeTestSuite.sh
> +StatusOperator=$(echo $?)
just say 
StatusOperator=$?

2020-01-14 22:23 UTC, scottz64 approved these changes

2020-01-14 22:23 UTC, merged