Update the chaincode testing tool
hyperledger/fabric-test pull request #365
Opened 2022-01-24 11:32 UTC by mbwhite

Major update to the tool

Signed-off-by: Matthew B White <whitemat@uk.ibm.com>

2022-03-03 14:15 UTC, jt-nti requested changes
Looks like a great update to the chaincode integration tool- just a few comments

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/CONTRIBUTORS.md
> -# Contributing
It looks like this file just had the wrong name: CONTRIBUTORS.md vs CONTRIBUTING.md
I think there's still some useful information in it which looks like it will get lost if it's deleted instead of being renamed/updated.

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/README.md
>  There are a set of different 'gherkin features' that drive tests for different aspects of the implementation. Each of these features will use one or more Fabric infrastructures and will use one or of
Typo, although not introduced by this PR :)

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/README.md
> +Update the configuration, and then rerun the same command. This will run the default set of tags `@basic-checks or @advanced-types or @metadata-checks`
Not sure about the command doing different things like this- would prefer an `--init` option or similar to do the config/test files thing.

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/README.md
> +On first usage, this will copy to current directory the configuration file `cucumber.js`, and the `features` directory with the gherkin tests. It is expected that the `cucumber.js` file will be updat
Why do the tests get copied out like this? Won't this mean that tests will diverge over time?

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/cucumber.js
> +const TEST_NETWORK_DIR='/home/matthew/github.com/hyperledger/fabric-samples/test-network'
I know this is a sample/template but it would be much nicer to provide workable defaults, i.e. `fabric-samples` under the home directory

Similar for other `/home/matthew` paths below

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/features/feature-1-basic-checks.feature
> +        And  Acting as Organization "Org1" user "User1"
Think it's just a cosmetic thing but there are lots of scenarios starting with `And` instead of `Given` or `When` which doesn't seem right

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/features/feature-2-advanced-types.feature
> +# TO FIX
To fix? In the test tool, or chaincode implementation(s)? It would be better to skip the scenario when running the test tool rather than commenting it out.

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/features/feature-3-transaction-hooks.feature
> +@transaction-hooks  @notsupportedyet
👀

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/features/feature-5-private-data-collections.feature
> +@three-org @private-data-collections @notsupportedyet
👀

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/features/feature-6-metadata-checks.feature
> +        Then The metadata for the chaincode must meet the schema
Probably just me but I misunderstood this initially. I think it's saying that the metadata should conform to the metadata schema, but I thought it meant match the expected metadata until I read the following checks.

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/package.json
> +    "fabric-chaincode-integration": "run.sh"
This doesn't seem like a good thing, and I think would be redundant with a `--init` option as mentioned above

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/package.json
> +    "build": "npm run format && npm run clean && npm run lint && echo Using TypeScript && tsc --version && tsc --pretty  && npm pack",
I think keeping the build to TypeScript compilation would be better, with a prebuild for linting potentially. I definitely don't think running a build should write formatting changes.

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/run.sh
> +#!/bin/bash
Hopefully this script can be deleted

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/src/cli.ts
> -#!/usr/bin/env node
Hopefully this file can be reinstated/updated in preference to the shell script

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/src/infrastructure/clientsdkproxy.ts
> +    // transientArgs: any; // TODO
👀

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/src/infrastructure/clientsdkproxy.ts
> +        //     return new MicrofabProvider();
TODO 👀

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/src/infrastructure/clientsdkproxy.ts
> +export interface ClientSDKProxy {
This seems like a mashup of a client SDK proxy and a Fabric network provider- how would that work using legacy SDK vs Gateway SDK (or even peer commands!) with the test network vs ansible vs mircofab vs minifabric? Could they be separated out?

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/src/infrastructure/testNetworkProvider.ts
> +        throw new Error('Method not implemented.');
But ccaas is the best chaincode! :)

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/src/interfaces/interfaces.ts
> +    // wallet: Wallet;
👀

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/src/step-definitions/hooks.ts
> +        // if ((scenario as any).gherkinDocument.uri !== (scenario.pickle as any).uri) {
👀

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/src/step-definitions/hooks.ts
> +        // global.CHAINCODES = this.workspace.chaincodes;
👀

2022-03-03 14:15 UTC, jt-nti commented on tools/chaincode-integration/src/step-definitions/identity/identity.ts
> +    public async registerUserNoAttr(orgName: string, identityName: string): Promise<void> {
Remove the identity stuff if it doesn't do anything?

2022-03-04 13:40 UTC, mbwhite commented on tools/chaincode-integration/README.md
> +On first usage, this will copy to current directory the configuration file `cucumber.js`, and the `features` directory with the gherkin tests. It is expected that the `cucumber.js` file will be updat
There is that potential yes;  it is useful to be able to modify the tests eg miss things out whilst testing. Or try other combinations.  So there is a degree of honesty!

It was proving tricky to get at the feature files when actually running - depending on where things where installed to.

However, maybe the copy out option could be remain, but default is use the inbuit ones.

2022-03-04 13:40 UTC, mbwhite commented on tools/chaincode-integration/README.md
> +Update the configuration, and then rerun the same command. This will run the default set of tags `@basic-checks or @advanced-types or @metadata-checks`
purely because I didn't want to write a complex bash script :-)

2022-03-04 13:41 UTC, mbwhite commented on tools/chaincode-integration/cucumber.js
> +const TEST_NETWORK_DIR='/home/matthew/github.com/hyperledger/fabric-samples/test-network'
that makes sense

2022-03-04 13:42 UTC, mbwhite commented on tools/chaincode-integration/features/feature-1-basic-checks.feature
> +        And  Acting as Organization "Org1" user "User1"
Can be easily changed..

2022-03-14 09:56 UTC, jt-nti approved these changes

2022-04-07 03:35 UTC, denyeart approved these changes

2022-04-07 03:36 UTC, merged